Add IaC job using checkmarx

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -7,67 +7,85 @@ on:
     types: [opened, synchronize, reopened, closed]
 
 jobs:
-  checkov-job:
+  # checkov-job:
+  #   runs-on: ubuntu-latest
+  #   name: checkov-action
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@master
+
+  #     - name: Run Checkov action
+  #       id: checkov
+  #       uses: bridgecrewio/checkov-action@master
+  #       with:
+  #         output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
+  #         output_file_path: snyk.json
+  #         download_external_modules: true
+  #         soft_fail: true # optional: do not return an error code if there are failed checks
+  #         framework: terraform
+
+  #     - name: Upload Json as artifact
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: snyk-report
+  #         path: snyk.json
+
+  # iac-dd-scan:
+  #   runs-on: ubuntu-latest
+  #   needs: checkov-job
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+
+  #     - name: Display downloaded files
+  #       run: ls
+
+  #     - name: Download SARIF report artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: snyk-report
+  #         path: .
+
+  #     - name: Display downloaded files
+  #       run: ls
+
+  #     - name: Use JSON from SARIF
+  #       run: |
+  #         mkdir -p ./reports
+  #         mv results_json.json ./reports/snyk.json
+
+  #     - name: Publish report
+  #       id: import-scan
+  #       uses: ivanamat/defectdojo-import-scan@v1
+  #       with:
+  #         token: ${{ secrets.DEFECTDOJO_TOKEN }}
+  #         defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
+  #         file: reports/snyk.json
+  #         scan_type: Checkov Scan
+  #         engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
+  #         push_to_jira: true
+
+  #     - name: Show final response output
+  #       run: |
+  #         set -e
+  #         printf '%s\n' '${{ steps.import-scan.outputs.response }}'
+
+  checkmarx-job:
     runs-on: ubuntu-latest
-    name: checkov-action
+    name: checkmarx-iac
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@master
-
-      - name: Run Checkov action
-        id: checkov
-        uses: bridgecrewio/checkov-action@master
+      - uses: actions/checkout@v2
+      - name: Mkdir results-dir
+        # make sure results dir is created
+        run: mkdir -p results-dir
+      - name: run kics Scan
+        uses: Checkmarx/kics-github-action@v1.7.0
         with:
-          output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
-          output_file_path: snyk.json
-          download_external_modules: true
-          soft_fail: true # optional: do not return an error code if there are failed checks
-          framework: terraform
-
-      - name: Upload Json as artifact
-        uses: actions/upload-artifact@v2
+          path: "terraform"
+          output_path: results-dir
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
         with:
-          name: snyk-report
-          path: snyk.json
-
-  iac-dd-scan:
-    runs-on: ubuntu-latest
-    needs: checkov-job
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Display downloaded files
-        run: ls
-
-      - name: Download SARIF report artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: snyk-report
-          path: .
-
-      - name: Display downloaded files
-        run: ls
-
-      - name: Use JSON from SARIF
-        run: |
-          mkdir -p ./reports
-          mv results_json.json ./reports/snyk.json
-
-      - name: Publish report
-        id: import-scan
-        uses: ivanamat/defectdojo-import-scan@v1
-        with:
-          token: ${{ secrets.DEFECTDOJO_TOKEN }}
-          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
-          file: reports/snyk.json
-          scan_type: Checkov Scan
-          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
-          push_to_jira: true
-
-      - name: Show final response
-        run: |
-          set -e
-          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
+          sarif_file: results-dir/results.sarif
